[package]
name = "rusttwi"
version = "0.1.0"
authors = ["ksakiyama <k.sakiyama1@gmail.com>"]

[dependencies]
error-chain = "0.10.0"
env_logger = "0.5.9"
oauth-client = "0.3"
serde = "1.0.16"
serde_derive = "1.0.43"
serde_json = "1.0.16"
config = "0.8"
clap = "~2.31"
